### ISSUE TITLE
Cannot draw veritical and horizontal lines of 0 width stroke using PPath

### ISSUE THREAD

**Issue by mro** [piccolo2d/piccolo2d.java#221]
Originally reported on Google Code with ID 221

```
What steps will reproduce the problem?
1. Use the following code:
PPath line = PPath.createLine(5f, 10f, 5f, 100f);
line.setStroke(new BasicStroke(0));

2. The following code too:
PPath line = new PPath();
line.setStroke(new BasicStroke(0));
line.moveTo(5f, 10f);
line.lineTo(5f, 100f);

What is the expected output? What do you see instead?
A horizontal or vertical line of 1 pixel wide should be drawn  in any zoom level. However
the line just can not be seen!

What version of the product are you using? On what operating system?
Piccolo2d.java 1.3.1 is used on java 1.6.0_14-b08, Windows XP SP3.

```

Reported by `v116mo` on 2011-07-23 10:54:06

**Comment by v116mo** [comment]
In PNode.setBounds(), there is the logic to check line's width and height. With BasickStroke(0), it's width will be 0 for vertical lines, it's height will be 0 for horizontal lines. The bounds is reset to EMPTY. If the such checking is disabled. The issue is resolved. Hope it helps!

public boolean setBounds(final double x, final double y, final double width, final double height) {
        if (bounds.x != x || bounds.y != y || bounds.width != width || bounds.height != height) {
            bounds.setRect(x, y, width, height);

**//            if (width <= 0 || height <= 0) {
//                bounds.reset();
//            }**

            internalUpdateBounds(x, y, width, height);
            invalidatePaint();
            signalBoundsChanged();
            return true;
        }
        // Don't put any invalidating code here or else nodes with volatile
        // bounds will
        // create a soft infinite loop (calling Swing.invokeLater()) when they
        // validate
        // their bounds.
        return false;
    }
